---
title: "Machine Learning application - Chicago Divvy Bikes"
author: "Nishanth Gandhidoss, Raghavendran Shankar"
date: "21 March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
# installing the packages
# Function to Install packages
# checks the available.packages before
installNewPackage <- function(packageName) {
        if(packageName  %in% rownames(installed.packages()) == FALSE)
        {
                install.packages(packageName, repos = "http://cran.us.r-project.org", dependencies=TRUE)
        }
}

installNewPackage("ROCR")
installNewPackage("plyr")
installNewPackage("caret")
installNewPackage("pROC")
installNewPackage("ggplot2")
installNewPackage("tidyr")
installNewPackage("caTools")
installNewPackage("class")
installNewPackage("MLmetrics")
installNewPackage("rpart")
installNewPackage("rpart.plot")
installNewPackage("rattle")
installNewPackage("randomForest")
installNewPackage("e1071")
installNewPackage("TSA")
installNewPackage("forecast")

library(ROCR)
library(plyr)
library(caret)
library(pROC)
library(ggplot2)
library(tidyr)
library(caTools)
library(class)
library(MLmetrics)
library(rpart)
library(rpart.plot)
library(rattle)
library(randomForest)
library(e1071)
library(TSA)
library(forecast)
```

#### Chicago Divvy Bikes 

**Write something about divvy bikes.**

#### Loading the dataset



```{r Loading the data}
# Loading divvy trip data
divvy_trips_q1 <- read.csv('data/Divvy_Trips_2016_Q1Q2/Divvy_Trips_2016_Q1.csv')
divvy_trips_q3 <- read.csv('data/Divvy_Trips_2016_Q3Q4/Divvy_Trips_2016_Q3.csv')
divvy_trips_q4 <- read.csv('data/Divvy_Trips_2016_Q3Q4/Divvy_Trips_2016_Q4.csv')
divvy_trips_04 <- read.csv('data/Divvy_Trips_2016_Q1Q2/Divvy_Trips_2016_04.csv')
divvy_trips_05 <- read.csv('data/Divvy_Trips_2016_Q1Q2/Divvy_Trips_2016_05.csv')
divvy_trips_06 <- read.csv('data/Divvy_Trips_2016_Q1Q2/Divvy_Trips_2016_06.csv')

# Load divvy station data
divvy_stations_q1q2 <- read.csv('data/Divvy_Trips_2016_Q1Q2/Divvy_Stations_2016_Q1Q2.csv')
divvy_stations_q3 <- read.csv('data/Divvy_Trips_2016_Q3Q4/Divvy_Stations_2016_Q3.csv')
divvy_stations_q4 <- read.csv('data/Divvy_Trips_2016_Q3Q4/Divvy_Stations_2016_Q4.csv')
```


#### Merging the data frame



```{r Merging the data frame}
# Combining trip data for 2nd quarter
divvy_trips_q2 <- data.frame(rbind(divvy_trips_04,divvy_trips_05,divvy_trips_06))

# Adding quarter column to each dataset
divvy_trips_q1$quarter <- "Q1"
divvy_trips_q2$quarter <- "Q2"
divvy_trips_q3$quarter <- "Q3"
divvy_trips_q4$quarter <- "Q4"

# Merging and preprocessing 1st and 2nd quarter
divvy_trips_q1q2 <- data.frame(rbind(divvy_trips_q1, divvy_trips_q2))
divvy_q1q2 <- merge(divvy_trips_q1q2, divvy_stations_q1q2, by.x = "from_station_id", by.y = "id")
divvy_q1q2$name <- NULL
colnames(divvy_q1q2)[14:17] <- c("from_station_latitude", "from_station_longitude",
                                 "from_station_dpcapacity", "from_station_online_date")
divvy_q1q2 <- merge(divvy_q1q2, divvy_stations_q1q2, by.x = "to_station_id", by.y = "id")
divvy_q1q2$name <- NULL
colnames(divvy_q1q2)[18:21] <- c("to_station_latitude", "to_station_longitude", 
                                 "to_station_dpcapacity", "to_station_online_date")

# Merging and preprocessing 3rd and 4th quarter
divvy_q3 <- merge(divvy_trips_q3,divvy_stations_q3,by.x = "from_station_id",by.y = "id")
divvy_q3$name <- NULL
colnames(divvy_q3)[14:17] <- c("from_station_latitude", "from_station_longitude",
                               "from_station_dpcapacity", "from_station_online_date")
divvy_q3 <- merge(divvy_q3,divvy_stations_q3,by.x = "to_station_id",by.y = "id")
divvy_q3$name <- NULL
colnames(divvy_q3)[18:21] <- c("to_station_latitude", "to_station_longitude", 
                               "to_station_dpcapacity", "to_station_online_date")

divvy_q4 <- merge(divvy_trips_q4,divvy_stations_q4,by.x = "from_station_id",by.y = "id")
divvy_q4$name <- NULL
colnames(divvy_q4)[14:17] <- c("from_station_latitude", "from_station_longitude",
                               "from_station_dpcapacity", "from_station_online_date")
divvy_q4 <- merge(divvy_q4,divvy_stations_q4,by.x = "to_station_id",by.y = "id")
divvy_q4$name <- NULL
colnames(divvy_q4)[18:21] <- c("to_station_latitude", "to_station_longitude", 
                               "to_station_dpcapacity", "to_station_online_date")

divvy_q3q4 <- data.frame(rbind(divvy_q3,divvy_q4))

# Making into a single dataframe
divvy <- data.frame(rbind(divvy_q1q2, divvy_q3q4))
```


```{r Creating Seasonality}
divvy$month <- unlist(lapply(strsplit(as.character(divvy$starttime), "/"), function(x) x[1]))
divvy$month <- as.character(divvy$month)

divvy$Season[divvy$month == "9" | divvy$month == "10" 
             | divvy$month == "11" ] <- "Fall"
divvy$Season[divvy$month == "12" | divvy$month == "1" 
             | divvy$month == "2" ] <- "Winter"
divvy$Season[divvy$month == "3" | divvy$month == "4" 
             | divvy$month == "5" ] <- "Spring"
divvy$Season[divvy$month == "6" | divvy$month == "7" 
             | divvy$month == "8" ] <- "Summer"

divvy$Season <- factor(divvy$Season)
table(divvy$Season)
```



```{r Verifying for missing values}
sapply(divvy, function(x) sum(is.na(x)))
```


```{r Writing to a csv file}
if(!file.exists("data/divvy.csv")) {
    write.csv(divvy, "data/divvy.csv")
}
```




```{r}
#dummy check code
x <- divvy_q1q2$from_station_id[as.character(divvy_q1q2$from_station_name) != as.character(divvy_q1q2$name)]
unique(x)
dummy <- divvy_q1q2[divvy_q1q2$from_station_id %in% x, ]
q1_repeat_station <- unique(dummy$from_station_name)
q1_repeat_station2 <- unique(dummy$name)
missed_station_name <- data.frame(q1_repeat_station, q1_repeat_station2)
q1_repeat_station <- unique(dummy$from_station_name)
q1_repeat_station1 <- unique(dummy$name)
missed_station_nameq1q2 <- data.frame(q1_repeat_station, q1_repeat_station1)


x <- divvy_q3q4$from_station_id[as.character(divvy_q3q4$from_station_name) != as.character(divvy_q3q4$name)]
unique(x)
dummy <- divvy_q3q4[divvy_q3q4$from_station_id %in% x, ]
q1_repeat_station <- unique(dummy$from_station_name)
q1_repeat_station2 <- unique(dummy$name)
missed_station_name <- data.frame(q1_repeat_station, q1_repeat_station2)
q1_repeat_station <- unique(dummy$from_station_name)
q1_repeat_station1 <- unique(dummy$name)
missed_station_nameq3q4 <- data.frame(q1_repeat_station, q1_repeat_station1)
```

```{r}
# Setting the seed for reproduciablility
set.seed(294)

# NO of fold
k_fold <- 10

# Creating the folds variable in the data frame
# music$folds <- createFolds(music$Top10, k = n_fold, list = FALSE)
cv_index_list <- createFolds(divvy$usertype, k = k_fold, list = TRUE, returnTrain = FALSE)



# Intailize variables
total_acc <- c()
total_error_rate <- c()
total_AUC <- c()

# Running the Naive bayes with 10 - fold cross validation
# Accuracy, error, AUC are rounded off to two decimal points
naiveBayesModel <- function() {
    for(fold in 1:k_fold) {
        train_set <- divvy[-cv_index_list[[fold]], ] 
        test_set <- divvy[cv_index_list[[fold]], ] 
        
        # Fitting the Naive bayes model
        nb_fit <- naiveBayes(usertype ~ trip_id+quarter+gender+birthyear, data = train_set)
        
        # Calculating Accuracy. Error, AUC
        test_prediction <- predict(nb_fit, test_set, type = "class")
        
        accuracy <- round(Accuracy(test_prediction, test_set$usertype), 2)
        error_rate <- 1 - accuracy
        AUC <- round(AUC(test_prediction, test_set$usertype), 2)
        total_acc <- c(total_acc, accuracy)
        total_error_rate <- c(total_error_rate, error_rate)
        total_AUC <- c(total_AUC, AUC)
    }
    
    report <- data.frame(Fold = c(1:10), Accuracy = total_acc, Error_rate = total_error_rate, AUC = total_AUC)
    print(report)
    cat("==========================================================\n")
    print(paste("Overall accuracy is", round(sum(total_acc) / k_fold, 2), sep = " "))
    print(paste("Overall error is", round(sum(total_error_rate) / k_fold, 2), sep =" "))
    print(paste("Overall area under the curve(AUC) is", round(sum(total_AUC) / k_fold, 2), sep = " "))
    cat("\n==========================================================\n")
}
naiveBayesModel()
```

```{r Time Series model for Average Trip Duration}
ts_trip_duration <- data.frame(cbind(unlist(lapply(strsplit(as.character(divvy$starttime), "/"), function(x) paste0(x[1],"/",x[2]))),divvy$tripduration))
ts_trip_duration$X1 <- as.character(ts_trip_duration$X1)
ts_trip_duration$X2 <- as.numeric(ts_trip_duration$X2)
ts_trip_duration <- aggregate(ts_trip_duration$X2,list(ts_trip_duration$X1),mean)
colnames(ts_trip_duration) <- c("Date","trip_duration")
ts_trip_duration$Date <- unlist(lapply(strsplit(as.character(ts_trip_duration$Date),"/"),function(x) x[1]))
ts_trip_duration$Date <- sort(as.numeric(ts_trip_duration$Date))

# Converting to Time Series Model
date=c(2016,1,1)
ts_model1 <- ts(ts_trip_duration[,2],start=date,frequency=365.25)
plot(ts_model1,ylab = "Average Trip Duration",xlab = "Days",main = "Time Series model of Average Trip Duration for 2016")

# Forecasting
train_msts <- msts(data = ts_model1,seasonal.periods = c(31,365.25))
model <- tbats(train_msts)

# Forecast for 2017
plot(model$fitted.values)
```


**End of Assignment**